# 1. 베이스 이미지
FROM python:3.10-slim

# 2. 작업 디렉토리 생성
WORKDIR /app

# 3. 필수 시스템 패키지 설치 
RUN apt-get update && apt-get install -y \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

# 4. 라이브러리 설치
COPY requirements.txt .

RUN python -m pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

#모델 미리 다운로드 
RUN python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('clip-ViT-B-32')"


# 5. 소스 코드 복사
COPY . .

# 6. 포트 노출
EXPOSE 5000

# 7. 서버 실행
CMD ["python", "-u", "app.py"]